FROM ubuntu:26.04

ENV TZ=CST-8

COPY install.sh /

RUN rm -rf /bin/sh \
    && ln -s /bin/bash /bin/sh \
    && chmod +x /install.sh \
    && /install.sh \
    && apt update \
    && apt install -y locales language-pack-zh-hans \
    && locale-gen zh_CN.UTF-8 \
    && update-locale LANG=zh_CN.UTF-8 \
    && rm -rf /install.sh \
    && rm -rf /var/lib/apt/lists/*


ENV LANG=zh_CN.UTF-8
ENV LANGUAGE=zh_CN:zh
ENV LC_ALL=zh_CN.UTF-8