name: docker-build

on:
  workflow_dispatch:
    inputs:
      REPO_NAME:
        description: "仓库名"
        required: false
        type: choice
        options:
          - "debian13"
          - "python3"
          - "img-builder"
          - "freestyle"
        default: "debian13"
      TAG:
        description: "Tag名"
        required: false
        type: string
        default: "untagged"
      USE_CACHE:
        description: "是否使用构建缓存"
        required: false
        type: choice
        options:
          - "true"
          - "false"
        default: "true"
      GIT_URL:
        description: "Git地址"
        required: false
        type: string
        default: "https://gitea.rotigue.cn:9443/cloud/image-build.git"
      ORACLE_RESOURCE_HOST:
        description: "oracle的资源机器ip"
        required: false
        type: string
        default: "10.0.0.215"
      PUSH_LATEST:
        description: "是否推送latest"
        required: false
        type: choice
        options:
          - "true"
          - "false"
        default: "false"
      NAS_RESOURCE_HOST:
        description: "nas的资源机器ip"
        required: false
        type: string
        default: "192.168.60.100"


jobs:
  build-amd64:
    runs-on: nas
    container:
      image: registry.cn-hangzhou.aliyuncs.com/rotigue/img-builder:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Docker Build
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin
          git clone ${{ inputs.GIT_URL }} ${{ inputs.REPO_NAME }}
          cd ${{ inputs.REPO_NAME }}/docker-build
          chmod +x ./build.sh
          export RESOURCE_IP=${{ inputs.NAS_RESOURCE_HOST }}
          ./build.sh -x -r ${{ inputs.REPO_NAME }} -t ${{ inputs.TAG }} -c ${{ inputs.USE_CACHE }}

#  sync-amd64:
#    runs-on: nas
#    needs:
#      - build-amd64
#    container:
#      image: registry.cn-hangzhou.aliyuncs.com/rotigue/forgejo-runner:12-ssh
#    steps:
#      - name: Docker push
#        run: |
#          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ inputs.PUSH_BUILDER_HOST }} \
#          '
#          docker pull registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
#          docker tag registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
#          docker push rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
#          '

  sync-amd64:
    runs-on: oracle
    needs:
      - build-amd64
    container:
      image: rotigue/img-builder:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Docker pull and push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin
          docker pull registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
          docker tag registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
          docker push rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64


  build-arm64:
    runs-on: oracle
    container:
      image: rotigue/img-builder:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Docker Build
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin
          git clone ${{ inputs.GIT_URL }} ${{ inputs.REPO_NAME }}
          cd ${{ inputs.REPO_NAME }}/docker-build
          chmod +x ./build.sh
          export RESOURCE_IP=${{ inputs.ORACLE_RESOURCE_HOST }}
          ./build.sh -a -r ${{ inputs.REPO_NAME }} -t ${{ inputs.TAG }} -c ${{ inputs.USE_CACHE }}

#  sync-arm64:
#    runs-on: nas
#    needs:
#      - build-arm64
#    container:
#      image: registry.cn-hangzhou.aliyuncs.com/rotigue/forgejo-runner:12-ssh
#    steps:
#      - name: Docker push
#        run: |
#          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ inputs.PUSH_BUILDER_HOST }} \
#          '
#          docker pull registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64
#          docker tag registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64
#          docker push rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64
#          '

  sync-arm64:
    runs-on: oracle
    needs:
      - build-arm64
    container:
      image: rotigue/img-builder:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Docker pull and push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin
          docker pull registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64
          docker tag registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64
          docker push rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64


#  manifest:
#    needs:
#      - sync-amd64
#      - sync-arm64
#    runs-on: nas
#    container:
#      image: registry.cn-hangzhou.aliyuncs.com/rotigue/forgejo-runner:12-ssh
#    steps:
#      - name: Docker push
#        run: |
#          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ inputs.PUSH_BUILDER_HOST }} \
#          '
#          rm -rf ~/.docker/manifests
#          mkdir -p ~/.docker/manifests
#          docker manifest create rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }} rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
#          docker manifest push rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}
#          docker manifest create registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }} registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
#          docker manifest push registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}
#          '
#
#      - name: Push Latest
#        if: ${{ inputs.PUSH_LATEST == 'true' }}
#        run: |
#          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ inputs.PUSH_BUILDER_HOST }} \
#          '
#          rm -rf ~/.docker/manifests
#          mkdir -p ~/.docker/manifests
#          docker manifest create rotigue/${{ inputs.REPO_NAME }}:latest rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
#          docker manifest push rotigue/${{ inputs.REPO_NAME }}:latest
#          docker manifest create registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:latest registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
#          docker manifest push registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:latest
#          '
#
#      - name: Delete Tags
#        run: |
#          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ inputs.PUSH_BUILDER_HOST }} \
#          '
#          TOKEN=$(curl -s -X POST https://hub.docker.com/v2/users/login/ \
#              -H "Content-Type: application/json" \
#              -d "{\"username\":\"${{ secrets.DOCKER_USERNAME }}\",\"password\":\"${{ secrets.DOCKER_PASSWORD }}\"}" \
#              | jq -r .token)
#          curl -X DELETE \
#              -H "Authorization: JWT $TOKEN" \
#              https://hub.docker.com/v2/repositories/rotigue/${{ inputs.REPO_NAME }}/tags/${{ inputs.TAG }}-arm64/
#          curl -X DELETE \
#              -H "Authorization: JWT $TOKEN" \
#              https://hub.docker.com/v2/repositories/rotigue/${{ inputs.REPO_NAME }}/tags/${{ inputs.TAG }}-amd64/
#          '

  manifest:
    needs:
      - sync-amd64
      - sync-arm64
    runs-on: nas
    container:
      image: rotigue/img-builder:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin

      - name: Docker manifest
        run: |
          rm -rf ~/.docker/manifests
          mkdir -p ~/.docker/manifests
          docker manifest create rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }} rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
          docker manifest push rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}
          docker manifest create registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }} registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
          docker manifest push registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}

      - name: Push Latest
        if: ${{ inputs.PUSH_LATEST == 'true' }}
        run: |
          rm -rf ~/.docker/manifests
          mkdir -p ~/.docker/manifests
          docker manifest create rotigue/${{ inputs.REPO_NAME }}:latest rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
          docker manifest push rotigue/${{ inputs.REPO_NAME }}:latest
          docker manifest create registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:latest registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-arm64 registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:${{ inputs.TAG }}-amd64
          docker manifest push registry.cn-hangzhou.aliyuncs.com/rotigue/${{ inputs.REPO_NAME }}:latest

      - name: Delete Tags
        run: |
          TOKEN=$(curl -s -X POST https://hub.docker.com/v2/users/login/ \
              -H "Content-Type: application/json" \
              -d "{\"username\":\"${{ secrets.DOCKER_USERNAME }}\",\"password\":\"${{ secrets.DOCKER_PASSWORD }}\"}" \
              | jq -r .token)
          curl -X DELETE \
              -H "Authorization: JWT $TOKEN" \
              https://hub.docker.com/v2/repositories/rotigue/${{ inputs.REPO_NAME }}/tags/${{ inputs.TAG }}-arm64/
          curl -X DELETE \
              -H "Authorization: JWT $TOKEN" \
              https://hub.docker.com/v2/repositories/rotigue/${{ inputs.REPO_NAME }}/tags/${{ inputs.TAG }}-amd64/
#
#  deploy:
#    needs:
#      - manifest
#    runs-on: nas
#    container:
#      image: registry.cn-hangzhou.aliyuncs.com/rotigue/forgejo-runner:12-ssh
#    steps:
#      - name: Docker deploy
#        if: ${{ inputs.NEED_DEPLOY == 'true' }}
#        run: |
#          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ inputs.DEPLOY_HOST }} \
#          '
#          cd ${{ inputs.DEPLOY_COMPOSE_PATH }}
#          docker compose pull ${{ inputs.REPO_NAME }}
#          docker compose up -d ${{ inputs.REPO_NAME }}
#          '
