[program:freestyle]
autostart=True
autorestart=true
startretries=10000
redirect_stderr=True
command=/app/freestyle/bin/freestyle -d /app/freestyle/config -ext-ui %(ENV_UI_DIR)s
user=root
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
stdout_logfile=/app/freestyle/logs/freestyle.log
directory=/app/freestyle
priority=810