[program:fresh]
autostart=True
autorestart=true
startretries=10000
redirect_stderr=True
command=/usr/bin/python3 /home/admin/app/freestyle/bin/freestyle_config_update.py
user=root
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
stdout_logfile=/home/admin/app/freestyle/logs/fresh.log
directory=/home/admin/app/freestyle
priority=810