[program:dockerd]
autostart=true
autorestart=true
startretries=10000
redirect_stderr=true
command=/usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --data-root=/var/lib/docker --storage-driver=overlay2
user=root
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=20
stdout_logfile=/logs/dockerd.log
directory=/
priority=805
environment=
    HTTP_PROXY="http://192.168.60.240:7890",
    HTTPS_PROXY="http://192.168.60.240:7890",
    NO_PROXY="localhost,127.0.0.1,::1"